### ISSUE TITLE
The order of values is inverted after unpacking

### ISSUE THREAD

**Issue by wgigliotti** [scotmcp/mmo_essentials#1]
I made the above test with the scrip:

	var arr : Array[int] = [0, 1, 22, 0, 0, 0, 0]
	var pack = BittyBytes.new()
	var val = pack.pack(arr, 8)
	var narr = pack.unpack(val, 8)
		
	print("Before: " + str(arr))	
	print("Packed:" + str(val))
	print("After:" + str(narr))

and I got the results:

Before: [0, 1, 22, 0, 0, 0, 0]
Packed:72058788038836224
After:[0, 0, 0, 0, 22, 1, 0]

Then, I testes with the above array:
var arr : Array[int] = [0, 1, 22, 0, 0, 0, 0, 0]
an array with 8 values with 8 bits each

and got:
Before: [0, 1, 22, 0, 0, 0, 0, 0]
Packed:305664232521728
After:[0, 0, 0, 0, 0, 22]

After that i changed the func pack code for:

	func pack(array : Array[int], bit_length : int = 1) -> int:	
		var size = array.size()
		# Checking the array size to avoid missing values
		if (size * bit_length) >= 64:
			push_error("Array BufferOverflow")
		# Initialize buffer to tell unpack() when to stop
		var buffer : int = 1 << ( size * bit_length)
		for i in size:		
			buffer += (array[i]) << (i * bit_length)
		return buffer

The result of the first test:
Before: [0, 1, 22, 0, 0, 0, 0]
Packed:72057594039369984
After:[0, 1, 22, 0, 0, 0, 0]

**Comment by scotmcp** [comment]
This is intended function...I could add an option for endian ordering, but that will increase the CPU cost.
